apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: namespace-workflow-1743510837534
  labels:
    app.kubernetes.io/name: test
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: test
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000